spring.application.name=StudentManagement

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5434/studentdb
spring.datasource.username=postgres
spring.datasource.password=1234

# JDBC Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=8080

# File Upload Size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB
file.upload-dir=uploads/

spring.mail.host=mail.nimttgroup.com
spring.mail.port=465

spring.mail.username=suman@nimttgroup.com
spring.mail.password=Kolkata2026

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

logging.level.org.springframework.mail=DEBUG
logging.level.org.eclipse.angus.mail=DEBUG